version: "3.9"

services:
  frontend:
    image: teemukoivumaa/financial-viewer-front:1.0.1
    restart: always
    build: ./frontend
    environment:
      port: 8080
      backendport: 8081
    ports:
      - 3000:8080
  backend:
    image: teemukoivumaa/financial-viewer-back:1.0.1
    restart: always
    build: ./backend
    environment:
      port: 8081
    ports:
      - 3001:8081
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local
